// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClickEvent = `-- name: CreateClickEvent :exec
INSERT INTO analytics_events (
    link_id,
    ip_address,
    user_agent
)
VALUES (
    $1,
    $2,
    $3
)
`

type CreateClickEventParams struct {
	LinkID    pgtype.UUID
	IpAddress pgtype.Text
	UserAgent pgtype.Text
}

func (q *Queries) CreateClickEvent(ctx context.Context, arg CreateClickEventParams) error {
	_, err := q.db.Exec(ctx, createClickEvent, arg.LinkID, arg.IpAddress, arg.UserAgent)
	return err
}

const getLinkAnalytics = `-- name: GetLinkAnalytics :many
SELECT
    created_at,
    ip_address,
    user_agent
FROM analytics_events
WHERE link_id = $1
ORDER BY created_at DESC
`

type GetLinkAnalyticsRow struct {
	CreatedAt pgtype.Timestamp
	IpAddress pgtype.Text
	UserAgent pgtype.Text
}

func (q *Queries) GetLinkAnalytics(ctx context.Context, linkID pgtype.UUID) ([]GetLinkAnalyticsRow, error) {
	rows, err := q.db.Query(ctx, getLinkAnalytics, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinkAnalyticsRow
	for rows.Next() {
		var i GetLinkAnalyticsRow
		if err := rows.Scan(&i.CreatedAt, &i.IpAddress, &i.UserAgent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
