// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getClickTimeline = `-- name: GetClickTimeline :many
SELECT
    DATE(clicked_at) AS date,
    COUNT(*) AS clicks
FROM click_events
WHERE link_id = $1
GROUP BY DATE(clicked_at)
ORDER BY DATE(clicked_at)
`

type GetClickTimelineRow struct {
	Date   pgtype.Date
	Clicks int64
}

func (q *Queries) GetClickTimeline(ctx context.Context, linkID pgtype.UUID) ([]GetClickTimelineRow, error) {
	rows, err := q.db.Query(ctx, getClickTimeline, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClickTimelineRow
	for rows.Next() {
		var i GetClickTimelineRow
		if err := rows.Scan(&i.Date, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardSummary = `-- name: GetDashboardSummary :one
SELECT
    COUNT(*) AS total_links,
    COALESCE(SUM(click_count),0) AS total_clicks,
    COUNT(*) FILTER (WHERE active = true) AS active_links
FROM links
`

type GetDashboardSummaryRow struct {
	TotalLinks  int64
	TotalClicks interface{}
	ActiveLinks int64
}

func (q *Queries) GetDashboardSummary(ctx context.Context) (GetDashboardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSummary)
	var i GetDashboardSummaryRow
	err := row.Scan(&i.TotalLinks, &i.TotalClicks, &i.ActiveLinks)
	return i, err
}
