// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link_management.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const disableLink = `-- name: DisableLink :one
UPDATE links
SET active = FALSE,
    updated_at = NOW()
WHERE id = $1
AND user_id = $2
RETURNING id, original_url, short_code, title, click_count, expires_at, created_at, updated_at, user_id, active
`

type DisableLinkParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DisableLink(ctx context.Context, arg DisableLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, disableLink, arg.ID, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.Title,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Active,
	)
	return i, err
}

const enableLink = `-- name: EnableLink :one
UPDATE links
SET active = TRUE,
    updated_at = NOW()
WHERE id = $1
AND user_id = $2
RETURNING id, original_url, short_code, title, click_count, expires_at, created_at, updated_at, user_id, active
`

type EnableLinkParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) EnableLink(ctx context.Context, arg EnableLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, enableLink, arg.ID, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.Title,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Active,
	)
	return i, err
}

const getUserLinkByID = `-- name: GetUserLinkByID :one
SELECT id, original_url, short_code, title, click_count, expires_at, created_at, updated_at, user_id, active
FROM links
WHERE id = $1
AND user_id = $2
LIMIT 1
`

type GetUserLinkByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetUserLinkByID(ctx context.Context, arg GetUserLinkByIDParams) (Link, error) {
	row := q.db.QueryRow(ctx, getUserLinkByID, arg.ID, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.Title,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Active,
	)
	return i, err
}

const updateLinkURL = `-- name: UpdateLinkURL :one
UPDATE links
SET original_url = $1,
    updated_at = NOW()
WHERE id = $2
AND user_id = $3
RETURNING id, original_url, short_code, title, click_count, expires_at, created_at, updated_at, user_id, active
`

type UpdateLinkURLParams struct {
	OriginalUrl string
	ID          pgtype.UUID
	UserID      pgtype.UUID
}

func (q *Queries) UpdateLinkURL(ctx context.Context, arg UpdateLinkURLParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLinkURL, arg.OriginalUrl, arg.ID, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.Title,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Active,
	)
	return i, err
}
