// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (
    original_url,
    short_code
)
VALUES (
    $1,
    $2
)
RETURNING id, original_url, short_code, title, click_count, expires_at, created_at, updated_at, user_id, active
`

type CreateLinkParams struct {
	OriginalUrl string
	ShortCode   string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.OriginalUrl, arg.ShortCode)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.Title,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Active,
	)
	return i, err
}

const getLinkByShortCode = `-- name: GetLinkByShortCode :one
SELECT
    id,
    original_url,
    short_code,
    title,
    click_count,
    expires_at,
    created_at,
    updated_at
FROM links
WHERE short_code = $1
LIMIT 1
`

type GetLinkByShortCodeRow struct {
	ID          pgtype.UUID
	OriginalUrl string
	ShortCode   string
	Title       pgtype.Text
	ClickCount  int64
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetLinkByShortCode(ctx context.Context, shortCode string) (GetLinkByShortCodeRow, error) {
	row := q.db.QueryRow(ctx, getLinkByShortCode, shortCode)
	var i GetLinkByShortCodeRow
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.Title,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementClickCount = `-- name: IncrementClickCount :exec
UPDATE links
SET
    click_count = click_count + 1,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementClickCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementClickCount, id)
	return err
}
