// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (
    original_url,
    short_code
)
VALUES (
    $1,
    $2
)
RETURNING id, original_url, short_code, title, click_count, expires_at, created_at, updated_at
`

type CreateLinkParams struct {
	OriginalUrl string
	ShortCode   string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.OriginalUrl, arg.ShortCode)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.Title,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkByShortCode = `-- name: GetLinkByShortCode :one
SELECT id, original_url, short_code, title, click_count, expires_at, created_at, updated_at
FROM links
WHERE short_code = $1
LIMIT 1
`

func (q *Queries) GetLinkByShortCode(ctx context.Context, shortCode string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByShortCode, shortCode)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.Title,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
