// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID          pgtype.UUID
	OriginalUrl string
	ShortCode   string
	Title       pgtype.Text
	ClickCount  int64
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
