// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: redirect.sql

package db

import (
	"context"
)

const getRedirectLink = `-- name: GetRedirectLink :one
SELECT id, original_url, short_code, title, click_count, expires_at, created_at, updated_at, user_id, active
FROM links
WHERE short_code = $1
LIMIT 1
`

func (q *Queries) GetRedirectLink(ctx context.Context, shortCode string) (Link, error) {
	row := q.db.QueryRow(ctx, getRedirectLink, shortCode)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.Title,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Active,
	)
	return i, err
}
