// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserLink = `-- name: CreateUserLink :one
INSERT INTO links (
    user_id,
    original_url,
    short_code
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, original_url, short_code, title, click_count, expires_at, created_at, updated_at, user_id, active
`

type CreateUserLinkParams struct {
	UserID      pgtype.UUID
	OriginalUrl string
	ShortCode   string
}

func (q *Queries) CreateUserLink(ctx context.Context, arg CreateUserLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createUserLink, arg.UserID, arg.OriginalUrl, arg.ShortCode)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.Title,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Active,
	)
	return i, err
}

const deleteUserLink = `-- name: DeleteUserLink :exec
DELETE FROM links
WHERE id = $1
AND user_id = $2
`

type DeleteUserLinkParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteUserLink(ctx context.Context, arg DeleteUserLinkParams) error {
	_, err := q.db.Exec(ctx, deleteUserLink, arg.ID, arg.UserID)
	return err
}

const getUserLinks = `-- name: GetUserLinks :many
SELECT
    links.id, links.original_url, links.short_code, links.title, links.click_count, links.expires_at, links.created_at, links.updated_at, links.user_id, links.active,
    MAX(analytics_events.created_at) AS last_clicked_at
FROM links
LEFT JOIN analytics_events
ON links.id = analytics_events.link_id
WHERE links.user_id = $1
GROUP BY links.id
ORDER BY links.created_at DESC
`

type GetUserLinksRow struct {
	ID            pgtype.UUID
	OriginalUrl   string
	ShortCode     string
	Title         pgtype.Text
	ClickCount    int64
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	UserID        pgtype.UUID
	Active        bool
	LastClickedAt interface{}
}

func (q *Queries) GetUserLinks(ctx context.Context, userID pgtype.UUID) ([]GetUserLinksRow, error) {
	rows, err := q.db.Query(ctx, getUserLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserLinksRow
	for rows.Next() {
		var i GetUserLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortCode,
			&i.Title,
			&i.ClickCount,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Active,
			&i.LastClickedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
